#!/usr/bin/env python3
"""
run_gamp.py  —  Interactive GAMP PPP Run Wizard

Guides you through selecting an observation file, a processing scenario,
and precise products.  Each run gets its own isolated folder under
GAMP_work/runs/<station>_<scenario>_<timestamp>/ with all input files
copied in (renamed to GAMP-expected format), a generated run.cfg, and
results preserved in that folder.

USAGE (always run from C:\\PPP_PROJECT):
    python scripts/run_gamp.py

Results are saved to:
    GAMP_work/runs/<station>_<scenario>_<timestamp>/result/

To plot afterwards:
    python scripts/plot_gamp_enu.py GAMP_work/runs/<run>/result/<station>.pos

NOTES ON GAMP FILE NAMING
  GAMP auto-detects products from the obs folder by RINEX-2 naming convention:
    SP3/CLK : {ac}{GPS_WEEK}{DAY_OF_WEEK}.sp3 / .clk   e.g. cod24014.sp3
    ERP     : {ac}{GPS_WEEK}7.erp                       e.g. cod24017.erp
    Nav     : brdm{DOY}0.{YY}p                          e.g. brdm0150.26p
    IONEX   : CODG{DOY}0.{YY}I                          e.g. CODG0150.26I
    ATX     : igs14.atx  (GAMP knows up to igs14 era)
    SINEX   : igs{GPS_WEEK}.snx                         e.g. igs2401.snx
    DCB     : CAS0MGXRAP_{YEAR}{DOY}0000_01D_01D_DCB.BSX
  This wizard renames all copied files to these expected names.

GAMP AC LIST (for SP3/CLK/ERP auto-detection):
  igs, esa, cod, gfz, grg, jpl, gbm, com, grm, wum
  Files from other ACs (e.g. emr) will be renamed to 'cod' as fallback.
"""

import os
import re
import shutil
import subprocess
import sys
from datetime import date, timedelta
from datetime import datetime
from pathlib import Path

# ── Paths ────────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent   # C:\PPP_PROJECT
DATA_DIR = ROOT / "data"
PROD_DIR = ROOT / "products"
RUNS_DIR = ROOT / "GAMP_work" / "runs"
GAMP_EXE = Path(r"C:\Program Files (x86)\GAMP\GAMP\bin\Windows\gamp.exe")
GAMP_IGS14_FALLBACK = Path(
    r"C:\Program Files (x86)\GAMP\GAMP\Examples\2017244\igs14.atx")

# ── ANSI colours (Windows 10+ / all ANSI-capable terminals) ──────────────────
BOLD = "\033[1m"
CYAN = "\033[96m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
DIM = "\033[2m"
RESET = "\033[0m"

# ── ACs supported by GAMP's auto-detection ────────────────────────────────────
GAMP_AC_LIST = {"igs", "esa", "cod", "gfz",
                "grg", "jpl", "gbm", "com", "grm", "wum"}

# ── Scenario table ────────────────────────────────────────────────────────────
# inpfrq: GAMP frequency count — MUST be 1 for IF12, 2 for UC12/ion-tec
SCENARIOS = {
    "A": dict(
        name="Broadcast-only  (SPP)",
        desc="GPS · broadcast nav only · ~1-5 m  |  baseline / sanity check",
        posmode=0,   navsys=1,  ionoopt=1, inpfrq=1,
        needs=dict(sp3=False, clk=False, erp=False, dcb=False, gim=False),
    ),
    "B": dict(
        name="GPS Precise  (IF combination)",
        desc="GPS · precise orbit+clock · ~5-15 cm  |  classic float PPP",
        posmode=7,   navsys=1,  ionoopt=2, inpfrq=1,   # IF12 → inpfrq MUST be 1
        needs=dict(sp3=True,  clk=True,  erp=True,  dcb=False, gim=False),
    ),
    "C": dict(
        name="Multi-GNSS Uncombined  (recommended)",
        desc="GPS+GLO+GAL+BDS · UC12 · ~2-6 cm  |  best GAMP result",
        posmode=7,   navsys=45, ionoopt=4, inpfrq=2,   # UC12 → inpfrq MUST be 2
        needs=dict(sp3=True,  clk=True,  erp=True,  dcb=True,  gim=False),
    ),
    "D": dict(
        name="Multi-GNSS + GIM  (iono-constrained)",
        desc="GPS+GLO+GAL+BDS · UC + external IONEX · ~2-8 cm",
        posmode=7,   navsys=45, ionoopt=5, inpfrq=2,
        needs=dict(sp3=True,  clk=True,  erp=True,  dcb=True,  gim=True),
    ),
}

# ── Known reference coordinates (ITRF2020) for site.crd generation ───────────
# HKWS verified from MIT0OPSSNX_2026015_SOL.SNX  (h≈64m, correct for HK)
# Wrong old values gave h=-6592m → tropmodel height warning every epoch
KNOWN_REFS = {
    "HKWS": (-2430579.667,  5374285.542,  2418955.908),
    # SINEX ITRF2020 2026/015
    "ZIM2": (4331299.709,   567537.749,  4633133.837),
    "ABMF": (2919785.791, -5383744.959,  1774604.860),
    "BAKO": (-1836969.501,  6065616.960,  -716257.934),
    "BRUX": (4027881.790,   306998.072,  4919498.571),
}

# ── GAMP config template ──────────────────────────────────────────────────────
CFG_TEMPLATE = """\
# GAMP configuration  -  auto-generated by run_gamp.py
# Generated : {timestamp}
# Station   : {station}
# Scenario  : {scenario_key}  -  {scenario_name}
# Run dir   : {run_dir}
#
# File mapping (RINEX-3 original -> GAMP-expected name):
{file_map_comment}

obs file/folder     = 0                                %(0:file  1:folder)
                    = {obs_path}

start_time          = 0    2000/01/01  00:00:00.0       %(0:from obs  1:from inp)
end_time            = 0    2000/01/01  00:00:00.0
posmode             = {posmode}                          %(0:spp  6:ppp_kinematic  7:ppp_static)
soltype             = 0                                 %(0:forward  1:backward  2:combined-bf)
navsys              = {navsys}                          %(1:gps  4:glo  5:gps+glo  8:gal  16:qzs  32:bds)
gnsisb              = 1
gloicb              = 0
minelev             = 7.0
maxout              = 3
sampleprc           = 0
inpfrq              = {inpfrq}
ionoopt             = {ionoopt}                         %(0:off  1:brdc  2:IF12  3:UC1  4:UC12  5:ion-tec)
ionopnoise          = 1
ionconstraint       = {ionconstraint}
tropopt             = 3
tropmf              = 1
tidecorr            = 7
cycleslip_GF        = 1  0.00
cycleslip_MW        = 1  0.00
errratio(P/L GPS)   = 100.0
errratio(P/L GLO)   = 100.0
errratio(P/L BDS)   = 500.0
errratio(P/L GAL)   = 100.0
errratio(P/L QZS)   = 100.0
errmeas(L)          = 0.003
prcNoise(AMB)       = 1.0e-07
prcNoise(ZTD)       = 1.0e-04
prcNoise(ION)       = 4.0e-02
prcNoise(ION_GF)    = 1.0e-03

outdir              = result
output              = 21
     pos            = 1
     debug          = 1
     pdop           = 1
     elev           = 1
     dtrp           = 1
     ifamb          = 0
     wlamb_no       = 1
     wlamb_yes      = 1
     gf             = 1
     amb_cs         = 0
     resc1          = 1
     resp1          = 1
     resc2          = 1
     resp2          = 1
     resc3          = 0
     resp3          = 0
     stec           = 1
     isb            = 1
     ibm            = 0
     ifb            = 0
     ippp           = 1
"""


# =============================================================================
# UI helpers
# =============================================================================

def _enable_ansi():
    if sys.platform == "win32":
        import ctypes
        k = ctypes.windll.kernel32
        k.SetConsoleMode(k.GetStdHandle(-11), 7)


def banner():
    print(f"\n{CYAN}{BOLD}")
    print("  +================================================+")
    print("  |     GAMP PPP Run Wizard                        |")
    print(f"  |     Project root: {str(ROOT):<28s}  |")
    print("  +================================================+")
    print(RESET)


def section(title, step=None, total=4):
    prefix = f"  Step {step}/{total}  .  " if step else "  "
    print(f"\n{BOLD}{prefix}{title}{RESET}")
    print(f"  {'─' * 56}")


def _ask(prompt, valid=None, default=None):
    hint = f" [{'/'.join(valid)}]" if valid else ""
    if default:
        hint += f"  (default: {default})"
    while True:
        raw = input(f"\n  {YELLOW}>{RESET} {prompt}{hint}: ").strip()
        if not raw and default is not None:
            return default
        if not raw:
            continue
        if valid is None:
            return raw
        up = raw.upper()
        if up in [v.upper() for v in valid]:
            return up
        print(f"  {RED}  Choose from: {', '.join(valid)}{RESET}")


def _pick(items, prompt, label_fn=None, allow_none=False):
    if not items:
        print(f"  {RED}  No files found.{RESET}")
        return None
    for i, item in enumerate(items, 1):
        label = label_fn(item) if label_fn else str(item)
        star = f"  {CYAN}*{RESET}" if i == 1 else "   "
        print(f"  {DIM}{i:2d}.{RESET}{star} {label}")
    if allow_none:
        print(f"   {DIM}0.   [none / skip]{RESET}")
    while True:
        lo, hi = (0 if allow_none else 1), len(items)
        raw = input(f"\n  {YELLOW}>{RESET} {prompt} [{lo}-{hi}]: ").strip()
        try:
            idx = int(raw)
            if allow_none and idx == 0:
                return None
            if 1 <= idx <= len(items):
                return items[idx - 1]
        except ValueError:
            pass
        print(f"  {RED}  Enter a number.{RESET}")


# =============================================================================
# GPS calendar helpers
# =============================================================================

def gps_week_dow(year: int, doy: int):
    """Return (GPS_week, day_of_week) — day_of_week: 0=Sun … 6=Sat."""
    GPS_EPOCH = date(1980, 1, 6)
    obs_date = date(year, 1, 1) + timedelta(days=doy - 1)
    delta = (obs_date - GPS_EPOCH).days
    return delta // 7, delta % 7


# =============================================================================
# GAMP filename convention helpers
# =============================================================================

def _ac_from_r3(filename: str) -> str:
    """Extract lowercase 3-letter AC from RINEX-3 filename prefix."""
    return filename[:3].lower()


def _ac_gamp(filename: str) -> str:
    """Return AC if GAMP-compatible, else 'cod' as fallback."""
    ac = _ac_from_r3(filename)
    return ac if ac in GAMP_AC_LIST else "cod"


def gamp_sp3_name(filename: str, week: int, dow: int) -> str:
    return f"{_ac_gamp(filename)}{week:04d}{dow}.sp3"


def gamp_clk_name(filename: str, week: int, dow: int) -> str:
    return f"{_ac_gamp(filename)}{week:04d}{dow}.clk"


def gamp_erp_name(filename: str, week: int) -> str:
    return f"{_ac_gamp(filename)}{week:04d}7.erp"


def gamp_nav_name(year: int, doy: int) -> str:
    return f"brdm{doy:03d}0.{year % 100:02d}p"


def gamp_ionex_name(year: int, doy: int) -> str:
    return f"CODG{doy:03d}0.{year % 100:02d}I"


def gamp_atx_name() -> str:
    return "igs14.atx"     # GAMP only knows up to igs14 era


def gamp_snx_name(week: int) -> str:
    return f"igs{week:04d}.snx"


def gamp_dcb_name(year: int, doy: int) -> str:
    return f"CAS0MGXRAP_{year:04d}{doy:03d}0000_01D_01D_DCB.BSX"


def _is_rinex2_obs(name: str) -> bool:
    """True for RINEX 2 obs: {site4}{doy}{session}.{yy}o  e.g. cut02440.17o"""
    return bool(re.match(r"[a-z0-9]{4}\d{3}[0-9a-z]\.\d{2}[odg]$", name, re.I))


def gamp_name_for(role: str, path: Path, year: int, doy: int,
                  week: int, dow: int) -> str:
    """Return the GAMP-expected filename for a product."""
    if role == "sp3":
        return gamp_sp3_name(path.name, week, dow)
    elif role == "clk":
        return gamp_clk_name(path.name, week, dow)
    elif role == "erp":
        return gamp_erp_name(path.name, week)
    elif role == "nav":
        return gamp_nav_name(year, doy)
    elif role == "atx":
        return gamp_atx_name()
    elif role == "gim":
        return gamp_ionex_name(year, doy)
    elif role == "snx":
        return gamp_snx_name(week)
    elif role == "dcb":
        return gamp_dcb_name(year, doy)
    return path.name


# =============================================================================
# Obs file pre-processing
# =============================================================================

def strip_trailing_records(src: Path, dst: Path) -> int:
    """Copy RINEX obs file, stripping trailing special records (epoch flag 4+).

    GAMP's Windows binary (32-bit) fails to parse getLastTime() when a
    RINEX file ends with special event records (e.g. GLONASS frequency slot
    tables appended by Spider software).  Stripping them fixes the error:
      *** ERROR: norm(cts,6)<=1.0||norm(cte,6)<=1.0

    Returns the number of lines stripped.
    """
    with open(src, "r", encoding="ascii", errors="replace") as fh:
        lines = fh.readlines()

    # Find last real data epoch: line starts with '>' and has a 4-digit year
    last_epoch_line = 0
    for i, line in enumerate(lines):
        if line.startswith(">") and len(line) > 10:
            try:
                if float(line[2:6]) > 2000:
                    last_epoch_line = i
            except ValueError:
                pass

    # Extend to include all satellite obs lines after that epoch
    cutoff = last_epoch_line
    for i in range(last_epoch_line + 1, min(last_epoch_line + 200, len(lines))):
        if lines[i].startswith(">"):
            break
        cutoff = i

    n_stripped = len(lines) - cutoff - 1
    with open(dst, "w", encoding="ascii", newline="\n") as fh:
        fh.writelines(lines[: cutoff + 1])
    return n_stripped


# =============================================================================
# File discovery helpers
# =============================================================================

# RINEX 2: {site4}{doy}{session}.{yy}o  —  years 80-29 → 1980-2029
# RINEX 3: .rnx  (site9_R_{year}{doy}... naming handled by regex fallback below)
OBS_EXTS = {".rnx", ".obs"} | {f".{yy:02d}o" for yy in range(0, 30)}


def find_obs_files():
    if not DATA_DIR.exists():
        return []
    return sorted(
        [f for f in DATA_DIR.iterdir()
         if f.suffix.lower() in OBS_EXTS
         or re.match(r".*\.\d{2}[onqg]$", f.name, re.I)],
        key=lambda f: f.name,
    )


def extract_date(filename: str):
    """Return (year_int, doy_int) from filename, or (None, None)."""
    m = re.search(r"_(\d{4})(\d{3})0000_", filename)
    if m:
        return int(m.group(1)), int(m.group(2))
    m = re.match(r"[a-z0-9]{4}(\d{3})\d+\.\d{2}[onqg]", filename, re.I)
    if m:
        yr2 = int(re.search(r"\.(\d{2})[onqg]", filename, re.I).group(1))
        year = 2000 + yr2 if yr2 < 80 else 1900 + yr2
        return year, int(m.group(1))
    return None, None


def station_from_obs(filename: str) -> str:
    return filename[:4].upper()


def _rinex_version(path: Path):
    """Best-effort RINEX version read from first line; returns float or None."""
    try:
        with open(path, "r", encoding="ascii", errors="replace") as fh:
            line = fh.readline()
        return float(line[:9].strip())
    except Exception:
        return None


def _obs_date_from_header(path: Path):
    """Best-effort (year, doy) from TIME OF FIRST OBS in header.

    Works for both RINEX 2 and RINEX 3 when filename does not carry date.
    Returns (None, None) on failure.
    """
    try:
        with open(path, "r", encoding="ascii", errors="replace") as fh:
            for _ in range(300):
                line = fh.readline()
                if not line:
                    break
                if "TIME OF FIRST OBS" in line:
                    nums = re.findall(r"[-+]?\d+(?:\.\d+)?", line[:43])
                    if len(nums) >= 3:
                        y = int(float(nums[0]))
                        m = int(float(nums[1]))
                        d = int(float(nums[2]))
                        if y < 100:
                            y = 2000 + y if y < 80 else 1900 + y
                        doy = date(y, m, d).timetuple().tm_yday
                        return y, doy
                if "END OF HEADER" in line:
                    break
    except Exception:
        pass
    return None, None


def find_products_for_date(year: int, doy: int) -> dict:
    """Return dict of lists for each product type, filtered by date.

    Supports both:
      RINEX 3 long-name: COD0MGXFIN_{year}{doy}0000_...  (new, post-2019)
      RINEX 2 short-name: cod{week}{dow}.sp3              (old, GAMP-native)
    RINEX 4 nav files (BRD4*) are excluded -- GAMP cannot parse them.
    BSX DCB files are returned regardless of date (2017 BSX works for 2026).
    """
    r3_pattern = f"{year}{doy:03d}"
    gps_week, _dow = gps_week_dow(year, doy)
    r2_prefix = rf"[a-zA-Z0-9]{{3}}{gps_week:04d}"

    def _search(subdir, exts):
        d = PROD_DIR / subdir
        if not d.exists():
            return []

        def _match(f):
            if f.suffix.lower() not in exts:
                return False
            n = f.name
            if r3_pattern in n:
                return True
            if re.match(r2_prefix, n):
                return True
            return False

        return sorted([f for f in d.iterdir() if _match(f)], key=lambda f: f.name)

    def _search_nav(exts):
        """Like _search('nav') but excludes RINEX 4 files (BRD4* prefix),
        and explicitly includes classic RINEX-2 brdm{doy}0.{yy}p naming."""
        all_nav = _search("nav", exts)

        # Ensure classic RINEX-2 nav files are discoverable even if they don't
        # carry week/date tokens in long-name form.
        nav_dir = PROD_DIR / "nav"
        yy = year % 100
        brdm_pat = re.compile(rf"brdm{doy:03d}0\.{yy:02d}p$", re.I)
        if nav_dir.exists():
            for f in nav_dir.iterdir():
                if f.suffix.lower() in exts and brdm_pat.search(f.name):
                    if f not in all_nav:
                        all_nav.append(f)
            all_nav = sorted(all_nav, key=lambda p: p.name)

        rnx3 = [f for f in all_nav if not f.name.upper().startswith("BRD4")]
        rnx4 = [f for f in all_nav if f.name.upper().startswith("BRD4")]
        if rnx4:
            print(f"  {YELLOW}  Note: {len(rnx4)} RINEX-4 nav file(s) excluded "
                  f"(BRD4* -- not supported by GAMP):{RESET}")
            for f in rnx4:
                print(f"    {DIM}  - {f.name}{RESET}")
        return rnx3

    def _search_dcb():
        """BSX files (any date) first, then date-matched BIA/DCB files.
        Using a 2017 BSX for 2026 is intentional -- satellite DCBs are stable."""
        d = PROD_DIR / "dcb"
        if not d.exists():
            return []
        bsx = sorted([f for f in d.iterdir()
                      if f.suffix.lower() == ".bsx"], key=lambda f: f.name)
        other = sorted([f for f in d.iterdir()
                        if f.suffix.lower() in {".bia", ".dcb"}
                        and (r3_pattern in f.name
                             or re.match(r2_prefix, f.name))],
                       key=lambda f: f.name)
        return bsx + other

    atx_dir = PROD_DIR / "atx"
    atx_files = sorted(atx_dir.glob("*.atx"), key=lambda p: (p.name.lower()
                       != "igs14.atx", p.name.lower())) if atx_dir.exists() else []
    if not any(p.name.lower() == "igs14.atx" for p in atx_files) and GAMP_IGS14_FALLBACK.exists():
        # Expose known-good igs14.atx even if user has only igs20/igs20_* in products.
        atx_files = [GAMP_IGS14_FALLBACK] + atx_files

    return {
        "sp3": _search("sp3",   {".sp3"}),
        "clk": _search("clk",   {".clk"}),
        "erp": _search("erp",   {".erp"}),
        "gim": _search("ionex", {".inx", ".ionex",
                                 ".17i", ".18i", ".19i", ".20i", ".21i",
                                 ".22i", ".23i", ".24i", ".25i", ".26i"}),
        "nav": _search_nav({".rnx", ".p",
                            ".17p", ".18p", ".19p", ".20p", ".21p",
                            ".22p", ".23p", ".24p", ".25p", ".26p",
                            ".n", ".g", ".l"}),
        "atx": atx_files,
        "dcb": _search_dcb(),
        "snx": _search("snx",   {".snx"}),
    }


# File label helpers
# =============================================================================

def _label(path: Path, role: str = None, week: int = None,
           dow: int = None, year: int = None, doy: int = None) -> str:
    ac = path.name[:3].lower()
    gname = ""
    note = ""
    if role and year and doy and week is not None:
        gname_val = gamp_name_for(role, path, year, doy, week, dow)
        if gname_val != path.name:
            gname = f"  {DIM}-> {gname_val}{RESET}"
    if role == "dcb" and path.suffix.lower() == ".bia":
        note = f"  {RED}[BIA/OSB format — NOT compatible with GAMP, use BSX instead]{RESET}"
    elif role == "atx" and path.name.lower() != "igs14.atx":
        note = f"  {YELLOW}[may fail in old GAMP parser; prefer igs14.atx]{RESET}"
    elif role in ("sp3", "clk", "erp") and ac not in GAMP_AC_LIST:
        note = f"  {YELLOW}[AC '{ac}' not in GAMP list -> renamed to 'cod']{RESET}"
    return f"{path.name}  {DIM}[{ac}]{RESET}{gname}{note}"


# =============================================================================
# site.crd writer
# =============================================================================

def write_site_crd(run_dir: Path, station: str):
    su = station.upper()
    if su not in KNOWN_REFS:
        print(
            f"  {YELLOW}  Note: {su} not in KNOWN_REFS — no site.crd written{RESET}")
        return
    x, y, z = KNOWN_REFS[su]
    with open(run_dir / "site.crd", "w", newline="\n") as fh:
        fh.write("# Reference coordinates for accuracy evaluation\n")
        fh.write("# Source: ITRF2020\n")
        fh.write(f"{su:<4s}  {x:15.4f}  {y:15.4f}  {z:15.4f}\n")
    print(f"  {GREEN}  OK site.crd{RESET}  ({su} ITRF2020)")


# =============================================================================
# File copy helpers
# =============================================================================

def copy_file_as(src: Path, run_dir: Path, gamp_name: str, label: str) -> bool:
    if not src.exists():
        print(f"  {RED}  x {label}: not found ({src}){RESET}")
        return False
    dst = run_dir / gamp_name
    shutil.copy2(src, dst)
    size_mb = src.stat().st_size / 1_048_576
    if src.name != gamp_name:
        print(f"  {GREEN}  OK {label}{RESET}  "
              f"{DIM}{src.name} -> {gamp_name}  ({size_mb:.1f} MB){RESET}")
    else:
        print(f"  {GREEN}  OK {label}{RESET}  {DIM}({size_mb:.1f} MB){RESET}")
    return True


def copy_and_strip_obs(src: Path, run_dir: Path) -> str:
    """Copy obs file to run_dir.  RINEX 2 is copied directly (no trailing records
    possible).  RINEX 3 is stripped of any trailing special event records to
    prevent GAMP's norm(cte)<=1.0 error.  Returns destination filename."""
    dst_name = src.name
    rinex_ver = _rinex_version(src)
    is_rinex2 = (rinex_ver is not None and rinex_ver <
                 3.0) or _is_rinex2_obs(src.name)
    if is_rinex2:
        shutil.copy2(src, run_dir / dst_name)
        size_mb = src.stat().st_size / 1_048_576
        print(f"  {GREEN}  OK obs{RESET}  {DIM}(RINEX 2, {size_mb:.1f} MB){RESET}")
    else:
        n = strip_trailing_records(src, run_dir / dst_name)
        size_mb = (run_dir / dst_name).stat().st_size / 1_048_576
        if n > 0:
            print(f"  {GREEN}  OK obs{RESET}  "
                  f"{DIM}(RINEX 3, {size_mb:.1f} MB, stripped {n} trailing records){RESET}")
        else:
            print(
                f"  {GREEN}  OK obs{RESET}  {DIM}(RINEX 3, {size_mb:.1f} MB){RESET}")
    return dst_name


# =============================================================================
# Config generation
# =============================================================================

def write_cfg(run_dir: Path, obs_name: str, scenario_key: str,
              file_map: dict) -> Path:
    sc = SCENARIOS[scenario_key]
    obs_path = str(run_dir / obs_name).replace("/", "\\")
    ionconstraint = 1 if scenario_key == "D" else 0

    map_lines = [f"#   {orig}  ->  {gname}"
                 for orig, gname in file_map.items()] or ["#   (no renaming needed)"]

    content = CFG_TEMPLATE.format(
        timestamp=datetime.now().isoformat(sep=" ", timespec="seconds"),
        station=station_from_obs(obs_name),
        scenario_key=scenario_key,
        scenario_name=sc["name"],
        run_dir=str(run_dir).replace("/", "\\"),
        obs_path=obs_path,
        posmode=sc["posmode"],
        navsys=sc["navsys"],
        ionoopt=sc["ionoopt"],
        inpfrq=sc["inpfrq"],
        ionconstraint=ionconstraint,
        file_map_comment="\n".join(map_lines),
    )
    cfg = run_dir / "run.cfg"
    cfg.write_text(content, encoding="utf-8")
    return cfg


# =============================================================================
# Main wizard flow
# =============================================================================

def main():
    _enable_ansi()
    banner()

    if not GAMP_EXE.exists():
        print(f"{RED}ERROR: GAMP not found:\n  {GAMP_EXE}{RESET}")
        sys.exit(1)

    # ------------------------------------------------------------------
    # Step 1: Observation file
    # ------------------------------------------------------------------
    section("Select Observation File", step=1)
    obs_files = find_obs_files()
    if not obs_files:
        print(f"  {RED}No observation files found in {DATA_DIR}{RESET}")
        sys.exit(1)

    print(f"  Files in  {DIM}{DATA_DIR}{RESET}:\n")
    obs = _pick(obs_files, "Select obs file", label_fn=lambda f: f.name)
    if obs is None:
        sys.exit(0)

    station = station_from_obs(obs.name)
    year, doy = extract_date(obs.name)
    if year is None or doy is None:
        y_hdr, d_hdr = _obs_date_from_header(obs)
        if y_hdr is not None and d_hdr is not None:
            year, doy = y_hdr, d_hdr

    rinex_ver = _rinex_version(obs)
    is_rinex2 = (rinex_ver is not None and rinex_ver <
                 3.0) or _is_rinex2_obs(obs.name)
    if year is not None and doy is not None:
        date_info = f"{year}/DOY {doy:03d}"
    else:
        date_info = "date=unknown"
    print(f"\n  {GREEN}  Selected:{RESET}  {obs.name}  "
          f"{DIM}(station={station}, {date_info}){RESET}")
    if year is None:
        print(f"  {YELLOW}  Warning: could not extract date from filename{RESET}")

    if year and doy:
        gps_week, gps_dow = gps_week_dow(year, doy)
        dow_names = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
        print(
            f"  {DIM}  GPS week {gps_week}, DOW {gps_dow} ({dow_names[gps_dow]}){RESET}")
    else:
        gps_week = gps_dow = None

    # ------------------------------------------------------------------
    # Step 2: Scenario
    # ------------------------------------------------------------------
    section("Select Processing Scenario", step=2)
    if is_rinex2:
        print(f"  {YELLOW}RINEX-2 observation detected.{RESET}")
        print(f"  {YELLOW}  Note: GAMP often rejects all epochs with UC multi-GNSS "
              f"(C/D) on mixed RINEX-2 files.{RESET}")
        print(f"  {YELLOW}  Recommended for RINEX-2: Scenario B (GPS IF).{RESET}\n")

    recommended_key = "B" if is_rinex2 else "C"
    print()
    for key, sc in SCENARIOS.items():
        star = f"  {CYAN}*{RESET} recommended" if key == recommended_key else "  "
        print(f"  {BOLD}{key}{RESET}  {sc['name']}{star}")
        print(f"      {DIM}{sc['desc']}{RESET}\n")

    scenario_key = _ask("Enter scenario", valid=list(
        SCENARIOS.keys()), default=recommended_key)

    if is_rinex2 and scenario_key in ("C", "D"):
        print(f"\n  {YELLOW}Warning:{RESET} scenario {scenario_key} with RINEX-2 can produce "
              f"0 valid epochs (continuous GF cycle-slip rejection).")
        keep = _ask("Keep scenario anyway", valid=["Y", "N"], default="N")
        if keep == "N":
            scenario_key = "B"
            print(
                f"  {GREEN}  Switched to:{RESET}  B  -  {SCENARIOS['B']['name']}")

    sc = SCENARIOS[scenario_key]
    print(f"\n  {GREEN}  Selected:{RESET}  {scenario_key}  -  {sc['name']}")

    # ------------------------------------------------------------------
    # Step 3: Products
    # ------------------------------------------------------------------
    section("Select Precise Products", step=3)
    products = {}   # role -> Path

    if year:
        print(f"  Searching products/ for date {year}/{doy:03d} ...\n")
        avail = find_products_for_date(year, doy)
    else:
        avail = {k: []
                 for k in ["sp3", "clk", "erp", "gim", "nav", "atx", "dcb", "snx"]}

    def lbl(p, role):
        return _label(p, role=role, week=gps_week, dow=gps_dow,
                      year=year, doy=doy)

    def _prompt(role, display_label, required):
        """Show file list and return selected Path (or None if skipped)."""
        files = avail.get(role, [])

        if not files:
            if not required:
                print(f"  {DIM}  {display_label}: none found — skipping{RESET}")
                return None
            print(
                f"  {YELLOW}  {display_label}: no matching file in products/{role}/{RESET}")
            raw = input(
                f"  {YELLOW}>{RESET} Full path (or blank to skip): ").strip()
            return Path(raw) if raw else None

        print(f"\n  {display_label}:  ({len(files)} found)")
        if len(files) == 1:
            # Auto-select the only option, but show it clearly
            print(f"   {DIM} 1.   {lbl(files[0], role)}{RESET}")
            return files[0]
        # Multiple options — let user choose
        return _pick(files, f"Select {display_label}",
                     label_fn=lambda p: lbl(p, role),
                     allow_none=not required)

    if not any(sc["needs"].values()):
        print(f"  Scenario A uses broadcast nav only — no precise products needed.")
    else:
        if sc["needs"]["sp3"]:
            products["sp3"] = _prompt("sp3", "SP3 orbit", required=True)
        if sc["needs"]["clk"]:
            products["clk"] = _prompt("clk", "CLK clock", required=True)
        if sc["needs"]["erp"]:
            products["erp"] = _prompt(
                "erp", "ERP earth-rotation", required=True)
        if sc["needs"]["dcb"]:
            products["dcb"] = _prompt(
                "dcb",
                "DCB signal bias  (optional — GAMP expects CAS0MGXRAP_...BSX format)",
                required=False)
        if sc["needs"]["gim"]:
            products["gim"] = _prompt(
                "gim", "GIM ionosphere (IONEX)", required=True)

    # Nav always needed
    products["nav"] = _prompt("nav", "Broadcast navigation", required=True)

    # ATX — always selectable (user should choose)
    if not any(p.name.lower() == "igs14.atx" for p in avail.get("atx", [])):
        print(f"\n  {YELLOW}Warning:{RESET} no igs14.atx found in products/atx.")
        print(
            f"  {YELLOW}  Old GAMP builds often fail on igs20.atx (error in reading atx).{RESET}")

    products["atx"] = _prompt(
        "atx",
        "ATX antenna corrections  (will be saved as igs14.atx for GAMP)",
        required=(scenario_key != "A"))

    # SINEX — optional, auto-selected if available
    snx_files = avail.get("snx", [])
    if snx_files and gps_week:
        print(f"\n  {DIM}SINEX (reference coords for error column):{RESET}")
        print(
            f"   {DIM} 1.   {snx_files[0].name} -> {gamp_snx_name(gps_week)}{RESET}")
        products["snx"] = snx_files[0]
    else:
        products["snx"] = None

    # ------------------------------------------------------------------
    # Step 4: Review & Run
    # ------------------------------------------------------------------
    section("Review & Run", step=4)

    # Compute GAMP names and build the file-map for the config comment
    file_map = {}
    for role, path in products.items():
        if path and year and doy and gps_week is not None:
            gname = gamp_name_for(role, path, year, doy, gps_week, gps_dow)
            if path.name != gname:
                file_map[path.name] = gname

    run_dir = RUNS_DIR / \
        f"{station}_{scenario_key}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

    print(f"\n  {BOLD}Configuration:{RESET}")
    print(f"    Station   :  {station}")
    if year:
        print(f"    Date      :  {year}/DOY {doy:03d}  "
              f"(GPS week {gps_week}, day {gps_dow})")
    print(f"    Scenario  :  {scenario_key}  -  {sc['name']}")
    mode_names = ["SPP", "", "", "", "", "", "kinematic", "static"]
    print(f"    posmode   :  {sc['posmode']}  ({mode_names[sc['posmode']]})")
    iono_names = ["off", "brdc", "IF12", "UC1", "UC12", "ion-tec"]
    print(f"    ionoopt   :  {sc['ionoopt']}  ({iono_names[sc['ionoopt']]})")
    print(f"    inpfrq    :  {sc['inpfrq']}")
    print(f"    navsys    :  {sc['navsys']}")
    print(f"    Run dir   :  {run_dir}")
    print()
    for role, path in products.items():
        if path:
            gname = gamp_name_for(role, path, year, doy, gps_week, gps_dow) \
                if year else path.name
            tag = f"  -> {gname}" if path.name != gname else ""
            print(f"    {role:<8s} :  {path.name}{DIM}{tag}{RESET}")

    if file_map:
        print(
            f"\n  {DIM}  Products will be renamed to RINEX-2 convention for GAMP.{RESET}")

    # Old GAMP binaries are sensitive to nav format in PPP modes.
    nav_path = products.get("nav")
    nav_ver = _rinex_version(nav_path) if nav_path else None
    if scenario_key in ("B", "C", "D") and nav_ver is not None and nav_ver >= 3.0:
        print(
            f"\n  {YELLOW}Warning:{RESET} selected nav is RINEX {nav_ver:.2f} ({nav_path.name}).")
        print(f"  {YELLOW}  This GAMP build often throws 'rinex nav toc error' in PPP modes"
              f" and can end with 0 epochs.{RESET}")
        print(f"  {YELLOW}  Prefer true RINEX-2 broadcast nav (brdm***.{year % 100:02d}p)"
              f" or run Scenario A for this day.{RESET}")
        keep = _ask("Proceed with this PPP run anyway",
                    valid=["Y", "N"], default="N")
        if keep != "Y":
            print(f"\n  {YELLOW}  Aborted.{RESET}")
            sys.exit(0)

    confirm = _ask("Proceed?", valid=["Y", "N"], default="Y")
    if confirm != "Y":
        print(f"\n  {YELLOW}  Aborted.{RESET}")
        sys.exit(0)

    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "result").mkdir(exist_ok=True)

    # ------------------------------------------------------------------
    # Copy files
    # ------------------------------------------------------------------
    print(f"\n  {BOLD}Copying files to run directory ...\n{RESET}")
    obs_name = copy_and_strip_obs(obs, run_dir)

    role_labels = {
        "sp3": "sp3 (orbit)", "clk": "clk (clock)",
        "erp": "erp (earth-rotation)", "dcb": "dcb (signal bias)",
        "gim": "gim (IONEX)", "nav": "nav (broadcast)",
        "atx": "atx (antenna corrections)", "snx": "snx (SINEX ref coords)",
    }
    for role, path in products.items():
        if path and path.exists():
            gname = gamp_name_for(role, path, year, doy, gps_week, gps_dow) \
                if year else path.name
            copy_file_as(path, run_dir, gname, role_labels.get(role, role))

    # Copy adjacent day SP3/CLK if both were selected
    if year and doy and products.get("sp3") and products.get("clk"):
        print(
            f"\n  {DIM}Copying adjacent day SP3/CLK files (GAMP requirement)...{RESET}")
        copy_adjacent_sp3_clk(run_dir, year, doy,
                              products.get("sp3"), products.get("clk"))
    write_site_crd(run_dir, station)
    cfg_path = write_cfg(run_dir, obs_name, scenario_key, file_map)
    print(f"  {GREEN}  OK run.cfg{RESET}")

    # ------------------------------------------------------------------
    # Run GAMP
    # ------------------------------------------------------------------
    print(f"\n  {BOLD}Running GAMP ...\n{RESET}")
    print(f"  {DIM}  {GAMP_EXE}{RESET}")
    print(f"  {DIM}  {cfg_path}{RESET}\n")

    start = datetime.now()
    ret = subprocess.run([str(GAMP_EXE), str(cfg_path)], cwd=str(run_dir))
    elapsed = (datetime.now() - start).total_seconds()

    if ret.returncode == 0:
        print(
            f"\n  {GREEN}{BOLD}GAMP finished{RESET}  {DIM}({elapsed:.0f} s){RESET}")
    else:
        print(f"\n  {RED}GAMP exited with code {ret.returncode}{RESET}")

    # ------------------------------------------------------------------
    # Results summary
    # ------------------------------------------------------------------
    result_dir = run_dir / "result"
    pos_files = list(result_dir.glob("*.pos"))
    print(f"\n  {BOLD}Results:{RESET}")
    print(f"    Run folder   :  {run_dir}")
    print(f"    Results in   :  {result_dir}")
    if pos_files:
        for pf in pos_files:
            sz = pf.stat().st_size
            epochs = sum(
                1 for ln in pf.read_text(errors="replace").splitlines()
                if ln.strip() and not ln.startswith(("%", "#"))
            )
            print(f"    {GREEN}OK{RESET}  {pf.name}  "
                  f"{DIM}({epochs} epochs, {sz // 1024} KB){RESET}")
        print(f"\n  {BOLD}To plot:{RESET}")
        for pf in pos_files:
            rel = pf.relative_to(ROOT)
            print(f"    python scripts/plot_gamp_enu.py {rel}")
        print(f"\n  {BOLD}To open in rtkplot:{RESET}")
        for pf in pos_files:
            rel = pf.relative_to(ROOT)
            print(f"    python scripts/gamp2rtkplot.py --open {rel}")
    else:
        print(f"    {YELLOW}No .pos files found — check GAMP output above{RESET}")
    print()


def copy_adjacent_sp3_clk(run_dir: Path, year: int, doy: int,
                          sp3_selected: Path, clk_selected: Path):
    """Copy adjacent day (day-1, day+1) SP3/CLK files to run_dir.

    GAMP's findSp3File() extends time window ±2.5 hours, requiring 3 consecutive days.
    If day-1 or day+1 files missing -> all satellites have elev=0.0 -> 0 epochs produced.
    This function finds and copies the adjacent files to ensure full processing.
    """
    from datetime import date, timedelta

    def get_adj_doy(year: int, doy: int, offset: int):
        d = date(year, 1, 1) + timedelta(days=doy - 1 + offset)
        return d.year, d.timetuple().tm_yday

    def gps_week_dow_local(year: int, doy: int):
        GPS_EPOCH = date(1980, 1, 6)
        d = date(year, 1, 1) + timedelta(days=doy - 1)
        delta = (d - GPS_EPOCH).days
        return delta // 7, delta % 7

    def _pick_adjacent_file(prod_dir: Path, ext: str, y: int, d: int,
                            week: int, dow: int, preferred_ac: str):
        if not prod_dir.exists():
            return None

        r2_pat = re.compile(rf"^[a-z]{{3}}{week:04d}{dow}\.{ext}$", re.I)
        day_token = f"{y}{d:03d}"

        candidates = []
        for f in sorted(prod_dir.iterdir(), key=lambda p: p.name):
            if f.suffix.lower() != f".{ext}":
                continue
            name = f.name
            if r2_pat.match(name) or day_token in name:
                candidates.append(f)

        if not candidates:
            return None

        # Prefer same analysis center as day0 file choice.
        for f in candidates:
            if _ac_gamp(f.name) == preferred_ac:
                return f
        return candidates[0]

    copied_count = 0
    sp3_ac = _ac_gamp(sp3_selected.name)
    clk_ac = _ac_gamp(clk_selected.name)

    for offset, label in [(-1, "day-1"), (+1, "day+1")]:
        adj_year, adj_doy = get_adj_doy(year, doy, offset)
        adj_week, adj_dow = gps_week_dow_local(adj_year, adj_doy)
        sp3_src = _pick_adjacent_file(PROD_DIR / "sp3", "sp3", adj_year,
                                      adj_doy, adj_week, adj_dow, sp3_ac)
        clk_src = _pick_adjacent_file(PROD_DIR / "clk", "clk", adj_year,
                                      adj_doy, adj_week, adj_dow, clk_ac)

        sp3_dst = run_dir / f"{sp3_ac}{adj_week:04d}{adj_dow}.sp3"
        clk_dst = run_dir / f"{clk_ac}{adj_week:04d}{adj_dow}.clk"

        if sp3_src and not sp3_dst.exists():
            shutil.copy2(sp3_src, sp3_dst)
            size_mb = sp3_src.stat().st_size / 1_048_576
            print(f"  {GREEN}  OK sp3 ({label}){RESET}  "
                  f"{DIM}{sp3_src.name} -> {sp3_dst.name} ({size_mb:.1f} MB){RESET}")
            copied_count += 1
        elif not sp3_src:
            print(f"  {YELLOW}  Missing sp3 ({label}) in products/sp3{RESET}")

        if clk_src and not clk_dst.exists():
            shutil.copy2(clk_src, clk_dst)
            size_mb = clk_src.stat().st_size / 1_048_576
            print(f"  {GREEN}  OK clk ({label}){RESET}  "
                  f"{DIM}{clk_src.name} -> {clk_dst.name} ({size_mb:.1f} MB){RESET}")
            copied_count += 1
        elif not clk_src:
            print(f"  {YELLOW}  Missing clk ({label}) in products/clk{RESET}")

    if copied_count == 0:
        print(f"  {YELLOW}  Note: no adjacent day SP3/CLK copied{RESET}")


if __name__ == "__main__":
    main()
